// ------------------------------------------------------------------------------
//  <auto-generated>
//      This code was generated by Reqnroll (https://www.reqnroll.net/).
//      Reqnroll Version:2.0.0.0
//      Reqnroll Generator Version:2.0.0.0
// 
//      Changes to this file may cause incorrect behavior and will be lost if
//      the code is regenerated.
//  </auto-generated>
// ------------------------------------------------------------------------------
#region Designer generated code
#pragma warning disable
namespace MaichessMatchMakerService.Tests.Features
{
    using Reqnroll;
    using System;
    using System.Linq;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Reqnroll", "2.0.0.0")]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public partial class QueueingServiceQueueEntryStatusAndDequeueLogicFeature : object, Xunit.IClassFixture<QueueingServiceQueueEntryStatusAndDequeueLogicFeature.FixtureData>, Xunit.IAsyncLifetime
    {
        
        private global::Reqnroll.ITestRunner testRunner;
        
        private static string[] featureTags = ((string[])(null));
        
        private static global::Reqnroll.FeatureInfo featureInfo = new global::Reqnroll.FeatureInfo(new System.Globalization.CultureInfo("en-US"), "Features", "QueueingService — queue entry, status, and dequeue logic", null, global::Reqnroll.ProgrammingLanguage.CSharp, featureTags);
        
        private Xunit.Abstractions.ITestOutputHelper _testOutputHelper;
        
#line 1 "QueueingService.feature"
#line hidden
        
        public QueueingServiceQueueEntryStatusAndDequeueLogicFeature(QueueingServiceQueueEntryStatusAndDequeueLogicFeature.FixtureData fixtureData, Xunit.Abstractions.ITestOutputHelper testOutputHelper)
        {
            this._testOutputHelper = testOutputHelper;
        }
        
        public static async System.Threading.Tasks.Task FeatureSetupAsync()
        {
        }
        
        public static async System.Threading.Tasks.Task FeatureTearDownAsync()
        {
        }
        
        public async System.Threading.Tasks.Task TestInitializeAsync()
        {
            testRunner = global::Reqnroll.TestRunnerManager.GetTestRunnerForAssembly(featureHint: featureInfo);
            if (((testRunner.FeatureContext != null) 
                        && (testRunner.FeatureContext.FeatureInfo.Equals(featureInfo) == false)))
            {
                await testRunner.OnFeatureEndAsync();
            }
            if ((testRunner.FeatureContext == null))
            {
                await testRunner.OnFeatureStartAsync(featureInfo);
            }
        }
        
        public async System.Threading.Tasks.Task TestTearDownAsync()
        {
            await testRunner.OnScenarioEndAsync();
            global::Reqnroll.TestRunnerManager.ReleaseTestRunner(testRunner);
        }
        
        public void ScenarioInitialize(global::Reqnroll.ScenarioInfo scenarioInfo)
        {
            testRunner.OnScenarioInitialize(scenarioInfo);
            testRunner.ScenarioContext.ScenarioContainer.RegisterInstanceAs<Xunit.Abstractions.ITestOutputHelper>(_testOutputHelper);
        }
        
        public async System.Threading.Tasks.Task ScenarioStartAsync()
        {
            await testRunner.OnScenarioStartAsync();
        }
        
        public async System.Threading.Tasks.Task ScenarioCleanupAsync()
        {
            await testRunner.CollectScenarioErrorsAsync();
        }
        
        async System.Threading.Tasks.Task Xunit.IAsyncLifetime.InitializeAsync()
        {
            await this.TestInitializeAsync();
        }
        
        async System.Threading.Tasks.Task Xunit.IAsyncLifetime.DisposeAsync()
        {
            await this.TestTearDownAsync();
        }
        
        [Xunit.SkippableFactAttribute(DisplayName="Invalid time format id — returns invalid input")]
        [Xunit.TraitAttribute("FeatureTitle", "QueueingService — queue entry, status, and dequeue logic")]
        [Xunit.TraitAttribute("Description", "Invalid time format id — returns invalid input")]
        public async System.Threading.Tasks.Task InvalidTimeFormatIdReturnsInvalidInput()
        {
            string[] tagsOfScenario = ((string[])(null));
            System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new System.Collections.Specialized.OrderedDictionary();
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("Invalid time format id — returns invalid input", null, tagsOfScenario, argumentsOfScenario, featureTags);
#line 5
  this.ScenarioInitialize(scenarioInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                testRunner.SkipScenario();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 6
    await testRunner.WhenAsync(("enqueue is called with userId \"user-a\" timeFormatId \"invalid\" opponentType \"human" +
                        "\" and botId \"\""), ((string)(null)), ((global::Reqnroll.Table)(null)), "When ");
#line hidden
#line 7
    await testRunner.ThenAsync("the enqueue result is invalid input \"invalid time_format_id\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [Xunit.SkippableFactAttribute(DisplayName="Invalid opponent type — returns invalid input")]
        [Xunit.TraitAttribute("FeatureTitle", "QueueingService — queue entry, status, and dequeue logic")]
        [Xunit.TraitAttribute("Description", "Invalid opponent type — returns invalid input")]
        public async System.Threading.Tasks.Task InvalidOpponentTypeReturnsInvalidInput()
        {
            string[] tagsOfScenario = ((string[])(null));
            System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new System.Collections.Specialized.OrderedDictionary();
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("Invalid opponent type — returns invalid input", null, tagsOfScenario, argumentsOfScenario, featureTags);
#line 9
  this.ScenarioInitialize(scenarioInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                testRunner.SkipScenario();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 10
    await testRunner.WhenAsync(("enqueue is called with userId \"user-a\" timeFormatId \"5+0\" opponentType \"alien\" an" +
                        "d botId \"\""), ((string)(null)), ((global::Reqnroll.Table)(null)), "When ");
#line hidden
#line 11
    await testRunner.ThenAsync("the enqueue result is invalid input \"opponent.type must be \'human\' or \'bot\'\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [Xunit.SkippableFactAttribute(DisplayName="Bot match with missing bot_id — returns invalid input")]
        [Xunit.TraitAttribute("FeatureTitle", "QueueingService — queue entry, status, and dequeue logic")]
        [Xunit.TraitAttribute("Description", "Bot match with missing bot_id — returns invalid input")]
        public async System.Threading.Tasks.Task BotMatchWithMissingBot_IdReturnsInvalidInput()
        {
            string[] tagsOfScenario = ((string[])(null));
            System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new System.Collections.Specialized.OrderedDictionary();
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("Bot match with missing bot_id — returns invalid input", null, tagsOfScenario, argumentsOfScenario, featureTags);
#line 13
  this.ScenarioInitialize(scenarioInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                testRunner.SkipScenario();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 14
    await testRunner.WhenAsync(("enqueue is called with userId \"user-a\" timeFormatId \"5+0\" opponentType \"bot\" and " +
                        "botId \"\""), ((string)(null)), ((global::Reqnroll.Table)(null)), "When ");
#line hidden
#line 15
    await testRunner.ThenAsync("the enqueue result is invalid input \"opponent.bot_id is required for bot matches\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [Xunit.SkippableFactAttribute(DisplayName="User already in queue — returns already queued")]
        [Xunit.TraitAttribute("FeatureTitle", "QueueingService — queue entry, status, and dequeue logic")]
        [Xunit.TraitAttribute("Description", "User already in queue — returns already queued")]
        public async System.Threading.Tasks.Task UserAlreadyInQueueReturnsAlreadyQueued()
        {
            string[] tagsOfScenario = ((string[])(null));
            System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new System.Collections.Specialized.OrderedDictionary();
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("User already in queue — returns already queued", null, tagsOfScenario, argumentsOfScenario, featureTags);
#line 17
  this.ScenarioInitialize(scenarioInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                testRunner.SkipScenario();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 18
    await testRunner.GivenAsync("the user \"user-a\" is already in a queue", ((string)(null)), ((global::Reqnroll.Table)(null)), "Given ");
#line hidden
#line 19
    await testRunner.WhenAsync(("enqueue is called with userId \"user-a\" timeFormatId \"5+0\" opponentType \"human\" an" +
                        "d botId \"\""), ((string)(null)), ((global::Reqnroll.Table)(null)), "When ");
#line hidden
#line 20
    await testRunner.ThenAsync("the enqueue result is already queued", ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [Xunit.SkippableFactAttribute(DisplayName="Human match — enqueues and returns queue token")]
        [Xunit.TraitAttribute("FeatureTitle", "QueueingService — queue entry, status, and dequeue logic")]
        [Xunit.TraitAttribute("Description", "Human match — enqueues and returns queue token")]
        public async System.Threading.Tasks.Task HumanMatchEnqueuesAndReturnsQueueToken()
        {
            string[] tagsOfScenario = ((string[])(null));
            System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new System.Collections.Specialized.OrderedDictionary();
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("Human match — enqueues and returns queue token", null, tagsOfScenario, argumentsOfScenario, featureTags);
#line 24
  this.ScenarioInitialize(scenarioInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                testRunner.SkipScenario();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 25
    await testRunner.GivenAsync("the user \"user-a\" is not in any queue", ((string)(null)), ((global::Reqnroll.Table)(null)), "Given ");
#line hidden
#line 26
    await testRunner.WhenAsync(("enqueue is called with userId \"user-a\" timeFormatId \"5+0\" opponentType \"human\" an" +
                        "d botId \"\""), ((string)(null)), ((global::Reqnroll.Table)(null)), "When ");
#line hidden
#line 27
    await testRunner.ThenAsync("the enqueue result is success with a queue token", ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
#line 28
    await testRunner.AndAsync("EnqueueAsync is called for user \"user-a\" with time format id \"5+0\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [Xunit.SkippableFactAttribute(DisplayName="Bot match — calls gRPC, stores entry, and returns queue token")]
        [Xunit.TraitAttribute("FeatureTitle", "QueueingService — queue entry, status, and dequeue logic")]
        [Xunit.TraitAttribute("Description", "Bot match — calls gRPC, stores entry, and returns queue token")]
        public async System.Threading.Tasks.Task BotMatchCallsGRPCStoresEntryAndReturnsQueueToken()
        {
            string[] tagsOfScenario = ((string[])(null));
            System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new System.Collections.Specialized.OrderedDictionary();
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("Bot match — calls gRPC, stores entry, and returns queue token", null, tagsOfScenario, argumentsOfScenario, featureTags);
#line 30
  this.ScenarioInitialize(scenarioInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                testRunner.SkipScenario();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 31
    await testRunner.GivenAsync("the user \"user-a\" is not in any queue", ((string)(null)), ((global::Reqnroll.Table)(null)), "Given ");
#line hidden
#line 32
    await testRunner.AndAsync("the match manager creates match \"match-xyz\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 33
    await testRunner.WhenAsync(("enqueue is called with userId \"user-a\" timeFormatId \"5+0\" opponentType \"bot\" and " +
                        "botId \"bot-1\""), ((string)(null)), ((global::Reqnroll.Table)(null)), "When ");
#line hidden
#line 34
    await testRunner.ThenAsync("the enqueue result is success with a queue token", ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
#line 35
    await testRunner.AndAsync("the CreateMatch gRPC request has white userId \"user-a\" and black botId \"bot-1\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 36
    await testRunner.AndAsync(("EnqueueBotMatchAsync is called for user \"user-a\" with time format id \"5+0\" and ma" +
                        "tch \"match-xyz\""), ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [Xunit.SkippableTheoryAttribute(DisplayName="Bot match propagates the resolved time format to the gRPC request")]
        [Xunit.TraitAttribute("FeatureTitle", "QueueingService — queue entry, status, and dequeue logic")]
        [Xunit.TraitAttribute("Description", "Bot match propagates the resolved time format to the gRPC request")]
        [Xunit.InlineDataAttribute("1+0", "60000", "0", new string[0])]
        [Xunit.InlineDataAttribute("3+2", "180000", "2000", new string[0])]
        [Xunit.InlineDataAttribute("5+0", "300000", "0", new string[0])]
        [Xunit.InlineDataAttribute("10+5", "600000", "5000", new string[0])]
        [Xunit.InlineDataAttribute("30+20", "1800000", "20000", new string[0])]
        public async System.Threading.Tasks.Task BotMatchPropagatesTheResolvedTimeFormatToTheGRPCRequest(string timeFormatId, string baseMs, string incrementMs, string[] exampleTags)
        {
            string[] tagsOfScenario = exampleTags;
            System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new System.Collections.Specialized.OrderedDictionary();
            argumentsOfScenario.Add("timeFormatId", timeFormatId);
            argumentsOfScenario.Add("baseMs", baseMs);
            argumentsOfScenario.Add("incrementMs", incrementMs);
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("Bot match propagates the resolved time format to the gRPC request", null, tagsOfScenario, argumentsOfScenario, featureTags);
#line 38
  this.ScenarioInitialize(scenarioInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                testRunner.SkipScenario();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 39
    await testRunner.GivenAsync("the user \"user-a\" is not in any queue", ((string)(null)), ((global::Reqnroll.Table)(null)), "Given ");
#line hidden
#line 40
    await testRunner.AndAsync("the match manager creates match \"match-x\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 41
    await testRunner.WhenAsync(string.Format(("enqueue is called with userId \"user-a\" timeFormatId \"{0}\" opponentType \"bot\" and " +
                            "botId \"bot-1\""), timeFormatId), ((string)(null)), ((global::Reqnroll.Table)(null)), "When ");
#line hidden
#line 42
    await testRunner.ThenAsync(string.Format("the CreateMatch request uses time format id \"{0}\" with base {1} and increment {2}", timeFormatId, baseMs, incrementMs), ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [Xunit.SkippableFactAttribute(DisplayName="Bot-vs-bot match — calls gRPC with two bot players")]
        [Xunit.TraitAttribute("FeatureTitle", "QueueingService — queue entry, status, and dequeue logic")]
        [Xunit.TraitAttribute("Description", "Bot-vs-bot match — calls gRPC with two bot players")]
        public async System.Threading.Tasks.Task Bot_Vs_BotMatchCallsGRPCWithTwoBotPlayers()
        {
            string[] tagsOfScenario = ((string[])(null));
            System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new System.Collections.Specialized.OrderedDictionary();
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("Bot-vs-bot match — calls gRPC with two bot players", null, tagsOfScenario, argumentsOfScenario, featureTags);
#line 54
  this.ScenarioInitialize(scenarioInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                testRunner.SkipScenario();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 55
    await testRunner.GivenAsync("the match manager creates match \"match-bvb\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "Given ");
#line hidden
#line 56
    await testRunner.WhenAsync("a bot-vs-bot match is created with white \"bot-a\" black \"bot-b\" time format \"5+0\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "When ");
#line hidden
#line 57
    await testRunner.ThenAsync("the enqueue result is success with match id \"match-bvb\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
#line 58
    await testRunner.AndAsync("the CreateMatch gRPC request has white botId \"bot-a\" and black botId \"bot-b\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [Xunit.SkippableFactAttribute(DisplayName="Bot-vs-bot match — invalid time format id is rejected")]
        [Xunit.TraitAttribute("FeatureTitle", "QueueingService — queue entry, status, and dequeue logic")]
        [Xunit.TraitAttribute("Description", "Bot-vs-bot match — invalid time format id is rejected")]
        public async System.Threading.Tasks.Task Bot_Vs_BotMatchInvalidTimeFormatIdIsRejected()
        {
            string[] tagsOfScenario = ((string[])(null));
            System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new System.Collections.Specialized.OrderedDictionary();
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("Bot-vs-bot match — invalid time format id is rejected", null, tagsOfScenario, argumentsOfScenario, featureTags);
#line 60
  this.ScenarioInitialize(scenarioInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                testRunner.SkipScenario();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 61
    await testRunner.WhenAsync(("a bot-vs-bot match is created with white \"bot-a\" black \"bot-b\" time format \"inval" +
                        "id\""), ((string)(null)), ((global::Reqnroll.Table)(null)), "When ");
#line hidden
#line 62
    await testRunner.ThenAsync("the enqueue result is invalid input \"invalid time_format_id\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [Xunit.SkippableFactAttribute(DisplayName="Bot-vs-bot match — empty bot id is rejected")]
        [Xunit.TraitAttribute("FeatureTitle", "QueueingService — queue entry, status, and dequeue logic")]
        [Xunit.TraitAttribute("Description", "Bot-vs-bot match — empty bot id is rejected")]
        public async System.Threading.Tasks.Task Bot_Vs_BotMatchEmptyBotIdIsRejected()
        {
            string[] tagsOfScenario = ((string[])(null));
            System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new System.Collections.Specialized.OrderedDictionary();
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("Bot-vs-bot match — empty bot id is rejected", null, tagsOfScenario, argumentsOfScenario, featureTags);
#line 64
  this.ScenarioInitialize(scenarioInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                testRunner.SkipScenario();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 65
    await testRunner.WhenAsync("a bot-vs-bot match is created with white \"\" black \"bot-b\" time format \"5+0\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "When ");
#line hidden
#line 66
    await testRunner.ThenAsync("the enqueue result is invalid input \"bot ids are required\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [Xunit.SkippableFactAttribute(DisplayName="Status — token not found — returns not found")]
        [Xunit.TraitAttribute("FeatureTitle", "QueueingService — queue entry, status, and dequeue logic")]
        [Xunit.TraitAttribute("Description", "Status — token not found — returns not found")]
        public async System.Threading.Tasks.Task StatusTokenNotFoundReturnsNotFound()
        {
            string[] tagsOfScenario = ((string[])(null));
            System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new System.Collections.Specialized.OrderedDictionary();
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("Status — token not found — returns not found", null, tagsOfScenario, argumentsOfScenario, featureTags);
#line 70
  this.ScenarioInitialize(scenarioInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                testRunner.SkipScenario();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 71
    await testRunner.GivenAsync("the queue entry \"tok-1\" does not exist", ((string)(null)), ((global::Reqnroll.Table)(null)), "Given ");
#line hidden
#line 72
    await testRunner.WhenAsync("get status is called for token \"tok-1\" by user \"user-a\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "When ");
#line hidden
#line 73
    await testRunner.ThenAsync("the get status result is not found", ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [Xunit.SkippableFactAttribute(DisplayName="Status — token belongs to different user — returns not found")]
        [Xunit.TraitAttribute("FeatureTitle", "QueueingService — queue entry, status, and dequeue logic")]
        [Xunit.TraitAttribute("Description", "Status — token belongs to different user — returns not found")]
        public async System.Threading.Tasks.Task StatusTokenBelongsToDifferentUserReturnsNotFound()
        {
            string[] tagsOfScenario = ((string[])(null));
            System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new System.Collections.Specialized.OrderedDictionary();
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("Status — token belongs to different user — returns not found", null, tagsOfScenario, argumentsOfScenario, featureTags);
#line 75
  this.ScenarioInitialize(scenarioInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                testRunner.SkipScenario();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 76
    await testRunner.GivenAsync("the queue entry \"tok-1\" belongs to user \"user-b\" and is waiting", ((string)(null)), ((global::Reqnroll.Table)(null)), "Given ");
#line hidden
#line 77
    await testRunner.WhenAsync("get status is called for token \"tok-1\" by user \"user-a\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "When ");
#line hidden
#line 78
    await testRunner.ThenAsync("the get status result is not found", ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [Xunit.SkippableFactAttribute(DisplayName="Status — entry is waiting — returns waiting with no match id")]
        [Xunit.TraitAttribute("FeatureTitle", "QueueingService — queue entry, status, and dequeue logic")]
        [Xunit.TraitAttribute("Description", "Status — entry is waiting — returns waiting with no match id")]
        public async System.Threading.Tasks.Task StatusEntryIsWaitingReturnsWaitingWithNoMatchId()
        {
            string[] tagsOfScenario = ((string[])(null));
            System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new System.Collections.Specialized.OrderedDictionary();
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("Status — entry is waiting — returns waiting with no match id", null, tagsOfScenario, argumentsOfScenario, featureTags);
#line 80
  this.ScenarioInitialize(scenarioInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                testRunner.SkipScenario();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 81
    await testRunner.GivenAsync("the queue entry \"tok-1\" belongs to user \"user-a\" and is waiting", ((string)(null)), ((global::Reqnroll.Table)(null)), "Given ");
#line hidden
#line 82
    await testRunner.WhenAsync("get status is called for token \"tok-1\" by user \"user-a\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "When ");
#line hidden
#line 83
    await testRunner.ThenAsync("the get status result is found with status \"waiting\" and no match id", ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [Xunit.SkippableFactAttribute(DisplayName="Status — entry is matched — returns matched with match id")]
        [Xunit.TraitAttribute("FeatureTitle", "QueueingService — queue entry, status, and dequeue logic")]
        [Xunit.TraitAttribute("Description", "Status — entry is matched — returns matched with match id")]
        public async System.Threading.Tasks.Task StatusEntryIsMatchedReturnsMatchedWithMatchId()
        {
            string[] tagsOfScenario = ((string[])(null));
            System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new System.Collections.Specialized.OrderedDictionary();
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("Status — entry is matched — returns matched with match id", null, tagsOfScenario, argumentsOfScenario, featureTags);
#line 85
  this.ScenarioInitialize(scenarioInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                testRunner.SkipScenario();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 86
    await testRunner.GivenAsync(("the queue entry \"tok-1\" belongs to user \"user-a\" and is matched with match \"match" +
                        "-xyz\""), ((string)(null)), ((global::Reqnroll.Table)(null)), "Given ");
#line hidden
#line 87
    await testRunner.WhenAsync("get status is called for token \"tok-1\" by user \"user-a\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "When ");
#line hidden
#line 88
    await testRunner.ThenAsync("the get status result is found with status \"matched\" and match id \"match-xyz\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [Xunit.SkippableFactAttribute(DisplayName="Dequeue — token not found — returns not found")]
        [Xunit.TraitAttribute("FeatureTitle", "QueueingService — queue entry, status, and dequeue logic")]
        [Xunit.TraitAttribute("Description", "Dequeue — token not found — returns not found")]
        public async System.Threading.Tasks.Task DequeueTokenNotFoundReturnsNotFound()
        {
            string[] tagsOfScenario = ((string[])(null));
            System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new System.Collections.Specialized.OrderedDictionary();
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("Dequeue — token not found — returns not found", null, tagsOfScenario, argumentsOfScenario, featureTags);
#line 92
  this.ScenarioInitialize(scenarioInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                testRunner.SkipScenario();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 93
    await testRunner.GivenAsync("the queue entry \"tok-1\" does not exist", ((string)(null)), ((global::Reqnroll.Table)(null)), "Given ");
#line hidden
#line 94
    await testRunner.WhenAsync("dequeue is called for token \"tok-1\" by user \"user-a\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "When ");
#line hidden
#line 95
    await testRunner.ThenAsync("the dequeue result is not found", ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [Xunit.SkippableFactAttribute(DisplayName="Dequeue — token belongs to different user — returns not found")]
        [Xunit.TraitAttribute("FeatureTitle", "QueueingService — queue entry, status, and dequeue logic")]
        [Xunit.TraitAttribute("Description", "Dequeue — token belongs to different user — returns not found")]
        public async System.Threading.Tasks.Task DequeueTokenBelongsToDifferentUserReturnsNotFound()
        {
            string[] tagsOfScenario = ((string[])(null));
            System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new System.Collections.Specialized.OrderedDictionary();
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("Dequeue — token belongs to different user — returns not found", null, tagsOfScenario, argumentsOfScenario, featureTags);
#line 97
  this.ScenarioInitialize(scenarioInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                testRunner.SkipScenario();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 98
    await testRunner.GivenAsync("the queue entry \"tok-1\" belongs to user \"user-b\" and is waiting", ((string)(null)), ((global::Reqnroll.Table)(null)), "Given ");
#line hidden
#line 99
    await testRunner.WhenAsync("dequeue is called for token \"tok-1\" by user \"user-a\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "When ");
#line hidden
#line 100
    await testRunner.ThenAsync("the dequeue result is not found", ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [Xunit.SkippableFactAttribute(DisplayName="Dequeue — valid request — removes entry and returns success")]
        [Xunit.TraitAttribute("FeatureTitle", "QueueingService — queue entry, status, and dequeue logic")]
        [Xunit.TraitAttribute("Description", "Dequeue — valid request — removes entry and returns success")]
        public async System.Threading.Tasks.Task DequeueValidRequestRemovesEntryAndReturnsSuccess()
        {
            string[] tagsOfScenario = ((string[])(null));
            System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new System.Collections.Specialized.OrderedDictionary();
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("Dequeue — valid request — removes entry and returns success", null, tagsOfScenario, argumentsOfScenario, featureTags);
#line 102
  this.ScenarioInitialize(scenarioInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                testRunner.SkipScenario();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 103
    await testRunner.GivenAsync("the queue entry \"tok-1\" belongs to user \"user-a\" and is waiting", ((string)(null)), ((global::Reqnroll.Table)(null)), "Given ");
#line hidden
#line 104
    await testRunner.WhenAsync("dequeue is called for token \"tok-1\" by user \"user-a\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "When ");
#line hidden
#line 105
    await testRunner.ThenAsync("the dequeue result is success", ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
#line 106
    await testRunner.AndAsync("RemoveAsync is called for token \"tok-1\" user \"user-a\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [System.CodeDom.Compiler.GeneratedCodeAttribute("Reqnroll", "2.0.0.0")]
        [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
        public class FixtureData : object, Xunit.IAsyncLifetime
        {
            
            async System.Threading.Tasks.Task Xunit.IAsyncLifetime.InitializeAsync()
            {
                await QueueingServiceQueueEntryStatusAndDequeueLogicFeature.FeatureSetupAsync();
            }
            
            async System.Threading.Tasks.Task Xunit.IAsyncLifetime.DisposeAsync()
            {
                await QueueingServiceQueueEntryStatusAndDequeueLogicFeature.FeatureTearDownAsync();
            }
        }
    }
}
#pragma warning restore
#endregion
